### ISSUE TITLE
Background color does not always appear as expected

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#58] opened 2017-02-24 21:04 UTC
0,0,0 = black; but any non-zero number seems to be treated as equal to 255 (grays and dark blacks, color shades cannot be set).

**Comment by wphicks** [comment] 2017-02-25 15:00
Given #50, I'm beginning to worry that this is an upstream bug. Will investigate further.

**Comment by shadoof** [comment] 2017-02-25 15:41
You mean a bug in Blender?

There are other ways (large colored objects) to make 'backgrounds' so: reducing the priority of this.

**Comment by wphicks** [comment] 2017-03-26 21:18
Merging #50 with this.

**Comment by wphicks** [comment] 2017-03-26 21:19
If someone has good steps for duplication, that would be helpful.

**Comment by wphicks** [comment] 2017-05-31 00:07
I believe this is resolved by 3c3737566f2b123166e5f8e6e78f736d7906b95d, but I am not *absolutely* certain, since I still haven't been able to reproduce it on my system. If someone with Mac access could give it a whirl, it would be much appreciated. I'm closing this, but please feel free to reopen it if anyone sees this as unresolved.

@shadoof, at some point we should look at this commit together. It would be very easy to allow the background to determine the "ambient" color for projects as well, and I rather like the effect it gives. I'm not sure about it for legacy compatibility, though, so I'd appreciate your thoughts.

**Closed as completed by wphicks** 2017-05-31 00:07 UTC
Labels: bug, beginner-friendly, testing-needed
