### ISSUE TITLE
sample_random.xml Traceback: key linV does not exist

### ISSUE THREAD

**Issue by purvigoel** [wphicks/Writing3D#30] opened 2016-07-18 15:26 UTC
sample_random.xml has three pieces of text: "left", "center", and "right." These randomly move forwards and backwards, towards and away from the user. When running this on cwapp.py, I get the following error after some debugging printouts: 

2016-07-18 11:14:54,387    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-18 11:14:54,404    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-18 11:14:54,420    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-18 11:14:54,437    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-18 11:14:54,437    DEBUG W3D PLACEMENT IS [0.0, -0.6096, 0.0] relative to Center at the end
2016-07-18 11:14:54,437    DEBUG W3D Index: 1
2016-07-18 11:14:54,437    DEBUG W3D Rotation Status: None with vector None and angle 0
2016-07-18 11:14:54,437    DEBUG W3D Up vector is: [0.0, 0.0, 0.3048]
2016-07-18 11:14:54,437    DEBUG W3D PLACEMENT IS [0.0, 0.6096, 0.0] relative to Center at start
2016-07-18 11:14:54,454    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-18 11:14:54,454    DEBUG W3D PLACEMENT IS [0.0, -0.6096, 0.0] relative to Center at the end
2016-07-18 11:14:54,454    DEBUG W3D Index: 2
2016-07-18 11:14:54,454    DEBUG W3D Rotation Status: None with vector None and angle 0
2016-07-18 11:14:54,454    DEBUG W3D Up vector is: [0.0, 0.0, 0.3048]

Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 102, in activate
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 102, in <listcomp>
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'

I went into Blender to see the line that was causing trouble, and it seems to be the following:

blender_object.position = [
                blender_object.position[i] + blender_object['linV'][i]
                for i in range(len(blender_object.position))]

**Comment by purvigoel** [comment] 2016-07-19 15:30
Quick update on this, I tried putting in a W3D_LOG.debug statement that printed out blender_object['linV'] in both start_string and end_string of movement.py and got the same traceback about the key "linV" not existing when running sample_random.xml. I tried running sample.xml with these debug statements as well, and got the same traceback again. So I don't think this is limited to sample_random.xml.

**Comment by wphicks** [comment] 2016-07-19 17:02
For the start string, did you put it before or after [linV is assigned to (160-165 and 190-194)](https://github.com/wphicks/Writing3D/blob/c79ef4bc1a198e0573f24122ee839c9c267f77fe/pyw3d/blender_actions/movement.py#L190-L194)? We don't always expect linV to be assigned. The question is why is it hitting the [code defined at 215-217](https://github.com/wphicks/Writing3D/blob/c79ef4bc1a198e0573f24122ee839c9c267f77fe/pyw3d/blender_actions/movement.py#L215-L217) without first hitting one of the linV assignments.

**Comment by purvigoel** [comment] 2016-07-19 17:08
Oh, I see. I originally had a debug statement before line 160, which caused a problem. I just moved it to after line 194, and this didn't cause an issue this time. However, the statement in the end_string still caused the aforementioned traceback.

**Comment by wphicks** [comment] 2016-07-19 18:00
Did you put it within the if statement at [line 238](https://github.com/wphicks/Writing3D/blob/c79ef4bc1a198e0573f24122ee839c9c267f77fe/pyw3d/blender_actions/movement.py#L238)?

**Comment by purvigoel** [comment] 2016-07-19 18:22
I first tried it with the debug statement within the if statement, and then again with the debug statement outside the if statement. Both resulted in that error!

**Comment by wphicks** [comment] 2016-07-19 18:42
Outside the if statement, we expect linV to be unassigned (it will only be assigned if we hit the same check at [line 157](https://github.com/wphicks/Writing3D/blob/c79ef4bc1a198e0573f24122ee839c9c267f77fe/pyw3d/blender_actions/movement.py#L157). Inside, that's much more interesting. Do you have a minimal example that reliably reproduces the error?

**Comment by purvigoel** [comment] 2016-07-19 19:16
Yikes, I think I misspoke. I messed around with the location of the W3D_LOG statements and I think I previously got a bit mixed up with the if statements. So just to correct my previous statement, linV is definitely unassigned outside the if statement. However, when I move the debug line within the if statement (if not self.duration), it is never printed out and there is no indication of a debug statement being there.

**Comment by wphicks** [comment] 2016-07-19 22:21
Can you clarify this a bit? We're still talking about [line 157](https://github.com/wphicks/Writing3D/blob/c79ef4bc1a198e0573f24122ee839c9c267f77fe/pyw3d/blender_actions/movement.py#L157), yes? You don't see the output from the debug statement within this if-block. When running which sample?

Are you still seeing a bug? If so, do you have a minimal example that reproduces it?

**Comment by purvigoel** [comment] 2016-07-20 05:07
Sorry! So the following is all through running sample.xml. Here's all the debug statements that I've been working with.

Debug Statement 1:
I think my line numbers are a little bit different from yours right now, but in the start_string there is an if/else statement for self.move_relative. This statement ends around line 147. At the same indentation, on the next line, is a script_text.extend() call, which starts with "blender_obect['angV'] = ("
I put a debug statement in this extend call, around line 157, to print out blender_object['linV']. This resulted in no error tracebacks, and had the following output.

2016-07-20 00:47:26,600    DEBUG W3D LINV IS CURRENTLY AT : [0.020320000251134236, 0.020320000251134236, -0.01016]

Debug Statement 2:

I put another debug statement around line 160. This was after the script_text.extend() I mentioned earlier, but before the next if statement: if "position" in self.placement. It was indented to the same margin as this if statement. This caused an error traceback; I assume it's because linV wasn't assigned.

Debug Statement 3:

I moved Debug Statement 2 down to the end of start_string, around line 202, right before try: script_text[0]=...
It was indented to the same margin as the "try:" command. This resulted in no error tracebacks, and had the following output:

2016-07-20 00:51:50,180    DEBUG W3D LINV IS CURRENTLY AT: [0.02065865878636638, -0.019981342554092407, 0.009990671277046203]

Debug Statement 4:

I put an additional debug statement at the start of end_string, around line 240, essentially right after script_text = [] is called. This also had no error tracebacks and had the following output:

2016-07-20 00:57:06,949    DEBUG W3D LINV IS CURRENTLY AT END: [0.020320000251134236, 0.020320000251134236, -0.01016]

Debug Statement 5:

The last debug statement was also in end_string, except it was within "if not self.duration:", so around line 270 for me. There were no error tracebacks, but I got no output. I'm guessing the if statement wasn't triggered then.

I'll double and triple check all of these several more times, just to make sure I haven't mixed anything up. But for now, I'm pretty sure this is all of it! I'll work on finding a minimal sample to reproduce it and see how far I can get with that.

**Comment by purvigoel** [comment] 2016-07-20 14:11
I've been working on a minimal sample and might have isolated a problem. The test is a simpler version of sample_random.xml. It has two pieces of MovingText. A timeline picks one of the two objects randomly, and moves it by 2 units. 

If I isolate the sample to just this, there are no errors or tracebacks. I think the problem comes with the next part. Mirroring sample_random.xml, this test then "(Re)starts Timeline". The code for this looks like:

`<TimedActions seconds-time="1.5">
                            <TimerChange name="1">
                                   <start/>
                            </TimerChange>
                     </TimedActions>
`
When this bit of code isn't in the file, there are no problems. When it is, an error occurs when running the test with cwapp.py, stating that the key linV does not exist. The error occurs after one movement occurs, I believe when the test goes back to restart the timeline in the above code. I made the duration of each change quite long so that this can be observed. Again the resulting traceback looks like this:

2016-07-20 10:05:51,838    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-20 10:05:51,844    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-20 10:05:51,860    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-20 10:05:51,881    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-20 10:05:51,881    DEBUG W3D PLACEMENT IS [0.0, -0.6096, 0.0] relative to Center at the end
2016-07-20 10:05:51,881    DEBUG W3D LINV IS CURRENTLY AT END: [0.0, -0.0067733333333333335, 0.0]
2016-07-20 10:05:51,905    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-20 10:05:51,906    DEBUG W3D PLACEMENT IS [0.0, -0.6096, 0.0] relative to Center at the end

_(this is when the first movement ends)_

Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 78, in activate
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'
2016-07-20 10:05:51,910    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-20 10:05:51,910    DEBUG W3D PLACEMENT IS [0.0, -0.6096, 0.0] relative to Center at the end
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 78, in activate
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'
2016-07-20 10:05:51,927    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-20 10:05:51,927    DEBUG W3D PLACEMENT IS [0.0, -0.6096, 0.0] relative to Center at the end
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 78, in activate
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'

I'll email over the test file.

**Comment by purvigoel** [comment] 2016-07-22 18:17
2016-07-22 14:14:55,573    DEBUG W3D LINV IN START STRING
2016-07-22 14:14:55,573    DEBUG W3D LINV AT LINE 160: [0.0, -0.02032, 0.0]
2016-07-22 14:14:55,609    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,609    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,623    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,640    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,664    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,673    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,690    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,712    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,723    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,740    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,756    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,777    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,790    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,806    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,828    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,840    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,857    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,873    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,890    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,906    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,929    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,940    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,956    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,979    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:55,990    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:56,006    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:56,030    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:56,040    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:56,056    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:56,079    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:56,080    DEBUG W3D LINV IS CURRENTLY AT END: [0.0, -0.02032, 0.0]
2016-07-22 14:14:56,080    DEBUG W3D LINV IN START STRING
2016-07-22 14:14:56,080    DEBUG W3D LINV AT LINE 160: [0.0, 0.02032, 0.0]
2016-07-22 14:14:56,090    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:56,090    DEBUG W3D LINV IS CURRENTLY AT END: [0.0, 0.02032, 0.0]
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 106, in activate
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 106, in <listcomp>
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'
2016-07-22 14:14:56,106    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:56,106    DEBUG W3D PLACEMENT IS [0.0, -0.6096, 0.0] relative to Center at the end
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 80, in activate
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'
2016-07-22 14:14:56,127    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:14:56,127    DEBUG W3D PLACEMENT IS [0.0, -0.6096, 0.0] relative to Center at the end
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):

**Comment by purvigoel** [comment] 2016-07-22 18:24
testRandom.xml output:

2016-07-22 14:22:23,463    DEBUG W3D LINV IN START STRING
2016-07-22 14:22:23,471    DEBUG W3D LINV AT LINE 160: [0.0, -0.0067733333333333335, 0.0]

2016-07-22 14:22:23,471    DEBUG W3D LINV IS CURRENTLY AT START STRING: [0.0, -0.0067733333333333335, 0.0]
2016-07-22 14:22:23,480    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,502    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,513    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,530    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,549    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,563    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,580    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,600    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,613    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,630    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,651    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,663    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,680    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,702    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,713    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,730    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,753    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,763    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,780    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,803    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,813    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,830    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,849    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,875    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,903    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,904    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,913    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,930    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,947    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,967    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,980    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:23,997    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,018    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,030    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,047    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,068    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,080    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,097    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,113    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,130    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,147    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,169    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,209    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,209    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,235    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,236    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,247    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,263    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,286    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,297    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,313    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,333    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,347    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,363    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,384    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,397    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,413    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,435    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,447    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,463    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,480    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,497    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,513    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,532    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,547    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,563    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,582    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,597    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,613    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,635    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,647    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,663    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,685    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,697    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,713    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,730    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,747    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,763    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,787    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,797    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,813    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,833    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,847    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,863    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,884    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,897    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,913    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,935    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,947    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:24,963    DEBUG W3D activate called on timeline_1 with status Continue

2016-07-22 14:22:24,963    DEBUG W3D LINV IS CURRENTLY AT END: [0.0, -0.0067733333333333335, 0.0]
2016-07-22 14:22:24,980    DEBUG W3D activate called on timeline_1 with status Continue

2016-07-22 14:22:24,980    DEBUG W3D LINV IS CURRENTLY AT END: [0.0, -0.0067733333333333335, 0.0]
2016-07-22 14:22:24,997    DEBUG W3D activate called on timeline_1 with status Continue

2016-07-22 14:22:24,997    DEBUG W3D LINV IS CURRENTLY AT END: [0.0, -0.0067733333333333335, 0.0]
2016-07-22 14:22:25,013    DEBUG W3D activate called on timeline_1 with status Continue

2016-07-22 14:22:25,013    DEBUG W3D LINV IS CURRENTLY AT END: [0.0, -0.0067733333333333335, 0.0]
2016-07-22 14:22:25,035    DEBUG W3D activate called on timeline_1 with status Continue

2016-07-22 14:22:25,035    DEBUG W3D LINV IS CURRENTLY AT END: [0.0, -0.0067733333333333335, 0.0]
2016-07-22 14:22:25,047    DEBUG W3D activate called on timeline_1 with status Continue

2016-07-22 14:22:25,047    DEBUG W3D LINV IS CURRENTLY AT END: [0.0, -0.0067733333333333335, 0.0]
2016-07-22 14:22:25,063    DEBUG W3D activate called on timeline_1 with status Continue

2016-07-22 14:22:25,063    DEBUG W3D LINV IS CURRENTLY AT END: [0.0, -0.0067733333333333335, 0.0]
2016-07-22 14:22:25,086    DEBUG W3D activate called on timeline_1 with status Continue

Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 80, in activate
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'
2016-07-22 14:22:25,097    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-22 14:22:25,097    DEBUG W3D PLACEMENT IS [0.0, -0.6096, 0.0] relative to Center at the end
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 80, in activate
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'

**Comment by purvigoel** [comment] 2016-07-25 14:10
I've been messing around with the testRandom.xml and found some really strange coincidences that I'll describe here.

When running the file, there are three things that the timeline can do, one of which is "good" and two of which are "bad": 
1. It can work as expected, looping back upon itself when each run is complete. ("Work")
2. It can fail in the form of the timeline simply stopping after a run through, rather than looping back upon itself ("Stop")
3. It can fail by breaking, with the traceback saying that the key linV does not exist ("Break").

What's interesting is that there seems to be a relationship between assigned durations of transitions and which of the three above scenarios happens. Previously, we only observed the 3rd option (the sample breaking), but the durations can be manipulated to get the 1st or 2nd options, in the following way.

testRandom.xml involves 3 separate durations:

The first is the start time of the timeline. This is around line 56, and looks like this:
`<TimedActions seconds-time="0.5">`

The second is the time it takes to complete the "move" action, defined around line 58. It looks like this:
`<Transition duration="0.5">`

The third is the start time for resetting the timeline, around line 68. It looks like this:
`<TimedActions seconds-time="1.1">`

Fiddling with these times can change which scenario (Work/Stop/Break) occurs, in the relationship:

"Timeline Start Time" + "Duration of Object Movement" =  "Timeline Reset Time"

When the two sides of the equation are equal, the 2nd scenario occurs: the timeline stops. When the right side of the equation is less than the left hand side of the equation, the 1st scenario occurs: the timeline works. When the right side of the equation is greater than the left hand side of the equation, the 3rd scenario occurs: the timeline breaks, with the whole "key linV does not exist" problem.

So I wonder if durations/times are part of the problem.

There's another weird consistency, which has to do with randomness. In testRandom.xml, the sample randomly picks one of two objects to move. This results in all of what was described above. However, if I remove randomness, so that there is only one object, we still see the previously described relationship causing the timeline to Stop:

"Timeline Start Time" + "Duration of Object Movement" =  "Timeline Reset Time"

Again, if the left hand side of the equation is less than the right hand side, the timeline Works. However, unlike in the tests for random picking of objects, if the left side of the equation is greater than the right side, the timeline just Stops, as opposed to Breaks. This is still a "fail" scenario, but there aren't any actual tracebacks.

So we only see the sample actually breaking with a traceback when we have a random sample. I'll send over the charts I made for what times made the timeline stop/break/work so that you can have a look!

**Comment by purvigoel** [comment] 2016-07-25 16:11
So just following off the duration observations I made in the last post, I made three follow-up observations.

**1. A "Work" Scenario Never Hits the End String**
I decided to look at the differences in debug logging for "Work"/"Stop"/"Break" situations. I used that chart I sent you to grab some times. So in a Random scenario, with a start time of 0.5, transition duration of 0.5, and timeline restart time of 0.9, I expected the timeline to "Work". (It did). The last bit of logging is the following:

2016-07-25 11:57:23,293    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:57:23,310    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:57:23,327    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:57:23,343    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:57:23,360    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:57:23,376    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:57:23,393    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:57:23,393    DEBUG W3D LINV IN START STRING
2016-07-25 11:57:23,393    DEBUG W3D LINV AT LINE 160: [0.0, -0.02032, 0.0]
2016-07-25 11:57:23,393    DEBUG W3D PLACEMENT IS [0.0, -0.6096, 0.0] relative to Center at THE start
2016-07-25 11:57:23,393    DEBUG W3D LINV IS CURRENTLY AT START STRING: [0.0, -0.02032, 0.0]
2016-07-25 11:57:23,410    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:57:23,426    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:57:23,445    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:57:23,460    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:57:23,476    DEBUG W3D activate called on timeline_1 with status Continue

So I think what's notable about this is that it never hits a logging statement in the end string (I put explicit W3D_debug.log statements in movement.py that tell me what string I'm currently in). 

**2. A "Stop" Scenario May Have To Do With run.blend Index**
I compared this to a situation where I bumped up the timeline restart time to 1.0 (according to the chart, this will make the program fail by the "Stop" scenario).

2016-07-25 11:50:50,795    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:50:50,812    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:50:50,828    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:50:50,845    DEBUG W3D activate called on timeline_1 with status Continue
2016-07-25 11:50:50,845    DEBUG W3D PLACEMENT IS [0.0, -0.6096, 0.0] relative to Center at the end
2016-07-25 11:50:50,845    DEBUG W3D LINV IS CURRENTLY AT END: [0.0, -0.02032, 0.0]
2016-07-25 11:50:50,862    DEBUG W3D activate called on timeline_1 with status Stop

Because we're restarting the timeline, I don't believe we should ever be hitting "Stop," as we never do in the previous "Work" situation.  So I looked at run.blend.

The status is reset to 'Start' in the if statement at line 114:
`if time >= 1.5 and index == 2:
            index += 1
            trigger = scene.objects['timeline_1']
            trigger['status'] = 'Start'`

The only place status is set to stop is at the very end, the if statement at line 127:

`if time >= 1.5:
            own['status'] = 'Stop'
            own['action_index'] = 0`

The difference between these is the index. If the first if statement is hit, then the timeline restarts. If it isn't, then the timeline Stops. And the only difference I see in these two if statements is again the index check. So that might pull back the curtain on what could be causing the differences between the "Stop"/"Work" scenarios.

**3. Typo?**
Also, something a little weird, I'm not sure if it's related, is the if statement on line 118:

`if time >= 1.5 and time < 1.5 and index >= 2:
            remaining_time = 1.5 - time
            pass`

Is this correct? I don't think this particular if statement will ever be hit because time cannot be both >=1.5 and <1.5. I also notice that remaining_time has values assigned to it numerous times through run.blend but I don't believe it's value is ever used within this actual file. I do think this is relevant considering that the Stop/Work/Break scenarios are so tied to the durations.

**Comment by wphicks** [comment] 2016-07-28 02:31
Resolved by 2af73be.

A quick note, because it is somewhat confusing. Occasionally (really, rather often), you will see lines in the Blender action logic like noted in point 3 ("Typo?") above. This is working as intended. These scripts are auto-generated, and it is least complicated to leave in these checks rather than having a special case during generation for one condition being mutually exclusive with another. This also avoids tricky floating point situations for time-based conditions.

**Closed as completed by wphicks** 2016-07-28 02:31 UTC
Labels: bug
