### ISSUE TITLE
Changing Lamp Color Through Timeline Causes Error

### ISSUE THREAD

**Issue by purvigoel** [wphicks/Writing3D#34] opened 2016-08-08 14:20 UTC
I used a minimum sample with a lamp shining on text. A timeline changes the color of the lamp from red to dark blue. The color change does actually occur when running the sample. However, once the color change is completed, I get the following traceback:

2016-08-08 10:22:49,584    DEBUG pyw3d Module bpy not found. Loading pyw3d.timeline as standalone
DEBUG:pyw3d:Module bpy not found. Loading pyw3d.timeline as standalone
2016-08-08 10:22:49,588    DEBUG pyw3d Module bpy not found. Loading pyw3d.activators.triggers.object_triggers as standalone
DEBUG:pyw3d:Module bpy not found. Loading pyw3d.activators.triggers.object_triggers as standalone
2016-08-08 10:22:49,590    DEBUG pyw3d Module bpy not found. Loading pyw3d.activators.triggers.object_triggers as standalone
DEBUG:pyw3d:Module bpy not found. Loading pyw3d.activators.triggers.object_triggers as standalone
2016-08-08 10:22:49,591    DEBUG pyw3d Module bpy not found. Loading pyw3d.activators.triggers.look_triggers as standalone
DEBUG:pyw3d:Module bpy not found. Loading pyw3d.activators.triggers.look_triggers as standalone
2016-08-08 10:22:49,592    DEBUG pyw3d Module bpy not found. Loading pyw3d.timeline as standalone
DEBUG:pyw3d:Module bpy not found. Loading pyw3d.timeline as standalone
2016-08-08 10:22:49,593    DEBUG pyw3d Module bpy not found. Loading pyw3d.objects as standalone
DEBUG:pyw3d:Module bpy not found. Loading pyw3d.objects as standalone
2016-08-08 10:22:49,599    DEBUG pyw3d Module bpy not found. Loading pyw3d.objects as standalone
DEBUG:pyw3d:Module bpy not found. Loading pyw3d.objects as standalone
2016-08-08 10:22:49,619     INFO pyw3d Cannot check relative reference to Light1
INFO:pyw3d:Cannot check relative reference to Light1
2016-08-08 10:22:49,619     INFO pyw3d Cannot check relative reference to Light1
INFO:pyw3d:Cannot check relative reference to Light1
found bundled python: /Users/purvigoel/Writing3D/blender-2.76-OSX_10.6-x86_64/blender.app/Contents/MacOS/../Resources/2.76/python
2016-08-08 10:22:50,892     INFO pyw3d Cannot check relative reference to Light1
2016-08-08 10:22:50,892     INFO pyw3d Cannot check relative reference to Light1
Info: No new files have been packed
Info: No new files have been packed
Info: Total files 0 | Changed 0 | Failed 0

Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 70, in activate
IndexError: list index out of range
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 70, in activate
IndexError: list index out of range
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 70, in activate
IndexError: list index out of range
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 70, in activate
IndexError: list index out of range
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 70, in activate
IndexError: list index out of range
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 70, in activate
IndexError: list index out of range
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 70, in activate
IndexError: list index out of range
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 70, in activate
IndexError: list index out of range
Python script error - object 'timeline_1', controller 'activate':

**Comment by wphicks** [comment] 2016-08-08 19:04
Great! Could you either post the xml (and the commit number for the version used to render it) or better yet, tell me what's at line 70 of timeline_1.py?

**Comment by purvigoel** [comment] 2016-08-09 03:43
Sure! Line 70 of timeline_1.py is:

new_color.append(blender_object.color[3])

The full if statement is:

`if time >= 1.0:
            blender_object = scene.objects['object_Light1']
            new_color = [0.0, 0.0, 0.4]
            if len(new_color) < 4:
                new_color.append(blender_object.color[3])
            blender_object.color = new_color
            own['random_choice'] = None`

I think the issue could be that when assigning a color in objects.py to a normal object (in apply_material), there's the code:

`color = [channel/255.0 for channel in self["color"]]
        color.append(int(self["visible"]))`

So len(color) = 3, I believe. But for a lamp, there is just:

`color = [channel/255.0 for channel in self["color"]]
        bpy.data.lamps[new_light_object.name].color = color`

Which is len(color)=3, so blender_object.color[3] wouldn't exist. I went in to the end_string of color.py and switched

if len(new_color) < 4:

in the if statement, to:

if len(new_color) < 3:

And that actually worked without any errors, but I don't know if doing so might affect other aspects of color.py. Please let me know if you want the xml and I can send it right away!

**Comment by wphicks** [comment] 2016-08-09 14:33
Ah, right. This is actually expected behavior, but it points out one other adjustment we'll have to make to the code. You should leave that particular check as is, since we're just checking to see if an alpha-value is assigned. 

What's going on here is that you've adjusted it so that only non-light objects are assigned a color (232a1777c4b609822aaef343f64fb0fcb92c3b56), but when dynamically changing the color, we currently query the object color, not the lamp color. So that's essentially part of what you're trying to fix up right now. Going to go ahead and close this since it's a result of a partially-implemented fix.

**Closed as completed by wphicks** 2016-08-09 14:33 UTC
