### ISSUE TITLE
Excessive warnings about relative references in parsing cwapp projects

### ISSUE THREAD

**Issue by purvigoel** [wphicks/Writing3D#22] opened 2016-06-22 15:21 UTC
I get very similar tracebacks ("Warning:root:Cannot check relative references...) when running most of the built-in samples on cwapp.py. Could it be a problem with how I am running it?

Traceback:

WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to frontlink
WARNING:root:Cannot check relative reference to frontlink
WARNING:root:Cannot check relative reference to rightlink
WARNING:root:Cannot check relative reference to rightlink
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to rightlink
WARNING:root:Cannot check relative reference to rightlink
WARNING:root:Cannot check relative reference to floorlink
WARNING:root:Cannot check relative reference to floorlink
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to floorlink
WARNING:root:Cannot check relative reference to floorlink
WARNING:root:Cannot check relative reference to leftlink
WARNING:root:Cannot check relative reference to leftlink
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to leftlink
WARNING:root:Cannot check relative reference to leftlink
WARNING:root:Cannot check relative reference to frontlink
WARNING:root:Cannot check relative reference to frontlink
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
found bundled python: /Users/purvigoel/Writing3D/blender-2.76-OSX_10.6-x86_64/blender.app/Contents/MacOS/../Resources/2.76/python
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to frontlink
WARNING:root:Cannot check relative reference to frontlink
WARNING:root:Cannot check relative reference to rightlink
WARNING:root:Cannot check relative reference to rightlink
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to rightlink
WARNING:root:Cannot check relative reference to rightlink
WARNING:root:Cannot check relative reference to floorlink
WARNING:root:Cannot check relative reference to floorlink
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to floorlink
WARNING:root:Cannot check relative reference to floorlink
WARNING:root:Cannot check relative reference to leftlink
WARNING:root:Cannot check relative reference to leftlink
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to leftlink
WARNING:root:Cannot check relative reference to leftlink
WARNING:root:Cannot check relative reference to frontlink
WARNING:root:Cannot check relative reference to frontlink
WARNING:root:Cannot check relative reference to movingtext
WARNING:root:Cannot check relative reference to movingtext
Info: Packed 5 files
Info: Packed 5 files
Info: Total files 5 | Changed 5 | Failed 0

Blender quit
Color management: using fallback mode for management
BLT_lang_init: 'locale' data path for translations not found, continuing
ndof: 3Dx driver not found
Detected GL_ARB_texture_env_combine
Detected GL_ARB_texture_cube_map
Detected GL_ARB_multitexture
Detected GL_ARB_shader_objects
Detected GL_ARB_vertex_shader
Detected GL_ARB_fragment_shader
Detected GL_ARB_vertex_program
Detected GL_ARB_depth_texture
Detected GL_EXT_separate_specular_color
found bundled python: /Users/purvigoel/Writing3D/blender-2.76-OSX_10.6-x86_64/blenderplayer.app/Contents/MacOS/../Resources/2.76/python
Error Totblock: 1

**Comment by wphicks** [comment] 2016-06-22 18:48
I split the first two parts of this off into issues #23 an #24. As for the warnings, that's not a problem with how you're running it (working as originally intended), but it's definitely annoying behavior. The issue is that certain features require us to know of the existence of other objects before they're necessarily loaded.

That is to say, if object A has a link which moves object B, then when we parse the project file, we won't be able to validate object A's link upon creation (since object B doesn't exist yet). One solution to this generic problem would be to validate on render rather than on item assignment, but then we wouldn't be able to warn a user that their input is potentially a problem. My vote is to change these from "warn" level logging events to "debug" level logging events and close the issue for now. We can always re-open later if we want to apply a more sophisticated solution.

**Comment by wphicks** [comment] 2016-07-19 00:01
Resolved by 72988d4f1ed5269414cdc923f3859a2a7a6c534b. Note that warnings will still show up unless debug level is set to "warn" in **init**.py.

**Closed as completed by wphicks** 2016-07-19 00:01 UTC
