### ISSUE TITLE
path-handling inconsistency between CW and Writing3D engines

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#52] opened 2017-02-16 00:01 UTC
For, e.g. fonts: The CW engine seems to want "./fonts/<fontname>" whereas the Writing3D engine wants "fonts/<fontname>".
  Suggested solution (especially as we try to maintain compatibility): allow Writing3D to accept and parse the "./fonts/<fontname>" form.
  (? Make sure this type of path-handling is generalized for all resource references ?)

**Comment by wphicks** [comment] 2017-02-16 00:22
Excellent, thanks for the report on this. It's definitely a genuine bug (I would expect the "./" to work), and I'll follow it up.

**Comment by wphicks** [comment] 2017-02-20 20:11
Could not reproduce this on a Linux machine (Ubuntu 16.04 for those of you playing at home). @purvigoel, could you test this on your system (after updating) and see what the deal is? If this is a Mac-only issue, I have a pretty good idea of how to work around it, but I want to confirm that we're seeing this on multiple Macs.

**Comment by shadoof** [comment] 2017-02-20 21:01
as of c55552a this is still an issue on my Mac although the behavior of the CWEditor.jar makes it very difficult to work out exactly what is happening. Anyway, default behavior *for W3D* should be:
- if path-to-font is specified, use it, else:
- expect to find fonts referenced by unqualified names in a folder at same level as xml called 'fonts'

**Comment by wphicks** [comment] 2017-02-20 22:07
This issue seems to have disappeared after further testing. Closing this and addressing your second point in #55, @shadoof. As always, please reopen if this issue reappears.

**Closed as completed** 2017-02-20 22:07 UTC
Labels: bug
