### ISSUE TITLE
Scaling of text appears different from legacy behavior

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#60] opened 2017-02-25 13:29 UTC
* Scaling for fonts may be correct but if you run sample 00 in both CW and W3D, the initial viewing position of W3D seems to be considerably closer. Thus: make camera start position of W3D correspond better with CW. (I have added grey 'bullets' to the the Cave corners for these samples.)
* Scaling for images is different (I believe). At scale 1, I think CW takes *any* image and creates a one-foot square rendering (padding other aspects) and then the Scale factor is relative to this. I don't know what W3D does.

**Comment by wphicks** [comment] 2017-02-25 14:59
Ah, you're right! CW does default to one-foot squares. I had thought it was pixel-count dependent. That's easily fixed.

As for the first, I'll have to look into it more closely.

**Comment by wphicks** [comment] 2017-03-26 21:14
If someone could test to see if bullet point 1 was resolved by the solution to #61, that would be helpful. Spinning the second point off into its own issue.

**Comment by wphicks** [comment] 2017-03-26 21:31
Duplicate of #54 and #67.

**Closed as completed by wphicks** 2017-03-26 21:31 UTC
Labels: legacy, testing-needed
